### PR TITLE
Fix Sign In

### LINKED ISSUE #156: Password Login Doesn't Work
session isn't updated after sign in

I've started some work here: https://github.com/hackwestern/hackwestern/tree/sign-in-is-cooked

### PR DESCRIPTION
**Pull request by hunterchen7**
closes #156 and #129

# Quick Overview of Changes

- add jwt to allow credential sign in to work
- fix sign in call in login page
- redirect to dashboard after email registration and log in
- add barebones sign out page

# Checklist

- [x] If any frontend changes were made, include a screenshot/demo in the overview
- [x] Checked all uses of changed component(s)/function(s)
- [x] If any changes were made to our backend services, at least one (happy path) unit test was added OR a `TODO` comment was added to create one.
- [x] Check that CI is passing.
- [x] If no (re-)reviews after 1-2 days, ping the web leads on the discord to remind them to review the PR.

### CODE REVIEW

**Comment by hunterchen7** [comment]
had to change to npm install or it doesn't like the package-lock lol

**Comment by hunterchen7** [comment]
@basokant can u try doing `npm install` from your side and changing back to `npm ci` to see if it likes your package lock any better?

**Review by ArsalaanAli — DISMISSED** [review]
lgtm

**Review by ArsalaanAli — APPROVED** [review]
lgtm

**Pull request merged**
